name: 'Pull Request Changelog'
description:
  'This action is designed to generate a changelog based on the merged pull
  requests between two git tags.'
author: 'Altevo'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'file-text'
  color: 'green'

# Define the inputs for your action
inputs:
  fromTag:
    description: 'The tag to start from'
    required: true
  toTag:
    description: 'The tag to end at'
    required: true
  token:
    description: 'The GitHub token to use'
    required: true

# Define the outputs for your action
outputs:
  changelog:
    description: 'Markdown formatted changelog'

# Define the main entrypoint for your action
runs:
  using: 'node20'
  main: 'dist/index.js'
